insert into project values(1, 'Intelligent Tourist Information System', '2015-08-29', 'Completed', 'Provide information to tourists based on their previous experiences', 'true');

insert into project values(2, 'Face Detection by Image Discriminating', '2016-01-23', 'Ongoing', 'Detection of a face in an image', 'false');

insert into project values(3, 'Scalable Analytics for IaaS Cloud Availability', '2016-01-09', 'Ongoing', '-', 'false');

insert into project values(4, 'Virtualization Technology for TCP/IP Offload Engine', '2016-01-23', 'Ongoing', '-', 'false');

insert into project values(5, 'Measuring Intent Security Problems in Android', '2015-12-30', 'Ongoing', 'Understand common flaws with the Intent system in android, classify and quantify their prevalence on a large dataset.', 'true'); 

insert into project values(6, 'Active Authentication based on mouse and keyboard usage', '2014-02-13', 'Completed', 'Write Javascript collection code and Python analysis code to distinguish mouse/keyboard usage patterns', 'false');

insert into project values(7, 'Market basket analysis for mining association rule.', '2015-12-31', 'Ongoing', 'Use data mining techniques to find patterns in customer transactions. Eg: If a person buys milk, he will buy bread and butter along with it.', 'false');

insert into project values(8, 'Prediction of movie success.', '2016-01-18', 'Ongoing', 'Use data mining techniques to analyse repetitive patterns and predict the success of the movie', 'false');

insert into project values(9, 'Employee Tracking System', '2015-06-03', 'Completed', 'Develop a signal transmitter whic will be provided to all employees and a system to track the signals', 'true');

insert into project values(10, 'Bus Tracking System', '2016-01-03', 'Ongoing', 'A system to find the location of a bus and notify the user about the next bus.', 'false');

insert into project values(11, 'Online Examination System', '2016-01-23', 'Ongoing', 'An intelligent system to monitor time, activities of the user and also provide a facility of evaluation(Giving partial marks where appropriate', 'false');

insert into project values(12, 'Hospital Management System', '2016-02-03','Ongoing', 'Detect fraud abuses in medical/hospitals,For making customer relationship, it helps for exploring the business. Doing patient activity analysis, how many visits they did and for which reason.To identify successful therapy for different illnesses.', 'false');

insert into project values(13, 'Online course portal', '2015-08-29', 'Completed', 'Provide video lectures, keep account of students and monitor their progress', 'true');

insert into Project values(66,'Literature Enhanced Automated Prediction of Functional Sites','2015-09-12','Ongoing','LEAP-FS is an approach that integrates high-throughput structure-based and text-based functional site predictions. Functional site identification plays an important role in targeted drug design','false');

insert into Project values(67,'Music Map','2015-02-23','Completed','Search for an artist or band and a list of albums will come up. Once you choose an album a circle pops up on the map. From there you can expand to get related albums, remove that album, or get more information','true');

insert into Project values(68,'TwittEarth','2016-01-14','Ongoing','TwittEarth shows live tweets from all over the world on a 3D globe. It’s a great visualization tool to see where tweets are coming from in real time and discover new people to follow. It’s also fascinating just to sit and watch','false');

insert into Project values(69,'Tag Browser','2015-02-22','Completed','Tag Browser allows you to search for a series of tags and see related tags. Clicking on a different tag brings up new related tags. You can zoom into the tag selected in the center of the screen by hovering and see images tagged with that word. It also gives a total image count and lets you browse by page.','true');

insert into Project values(70,'Wireless Network Based Wireless SCADA','2014-03-03','Completed','It is not possible to achieve manual control over multiple continuous processes going on in industries.  The proposed system is designed to achieve and control the multiple processes in large scale industries remotely by supervision. The SCADA is one of the great technologies in basic electronics projects which is used to monitor the remote area without human interference. In this project, using four temperature sensors formed as wireless sensor networks projects, which are located in various places. If sensor temperature increases at the set point of the GUI, then the relay is made to switch ON and OFF the heater (a lamp load) to maintain the set temperature.','true');

insert into Project values(71,'Medical Applications Based on Wireless Sensor Networks','2015-04-05','Ongoing','Nowadays, the health care system is highly complex. The proposed system is designed to provide ultimate solutions to the healthcare using the wireless sensor networks. This proposed system is used to monitor the patient’s health by wirelessly using RF technology. It is a very tedious method. In this proposed system transmitting module continuously reads patient’s body temperature through a digital temperature sensor, displays it on the LCD screen and sends it to the microcontroller which transmits the encoded serial data over the air by RF (radio frequency) through an RF module','false');

insert into Project values(72,'Wireless Sensors Based System for Home Energy Consumption','2016-01-01','Ongoing','A Wireless-sensor-network-based system is used in high energy requiring home appliances like white goods, audio/video devices, communication equipment, air conditioning systems, heating and cooling system, which make our homes one of the most critical areas for the impact of energy consumption in the natural environment. Zigbee home automation is a simple  mini project for ece studentswhich can be implemented for automatic control of home appliances','false');

insert into Project values(73,'E Commerce Product Rating Based On Customer Review Mining','2015-03-02','Completed',' Through online shopping many E-commerce enterprises were unable to know whether the customers are satisfied by the services provided by the firm.This boosts us to develop a system where various customers give reviews about the product and online shopping services, which in turn help the E-commerce enterprises and manufacturers to get customer opinion to improve service and merchandise through mining customer reviews. An algorithm could be used to track and manage customer reviews, through mining topics and sentiment orientation from online customer reviews.','true');

insert into Project values(74,'Website Evaluation Using Opinion Mining','2015-11-11','Ongoing','Here we propose an advanced Website Evaluation system that rates the website based on the opinion of the user. Website will be evaluated based on factors such genuineness of the website, timely delivery of the product after online transaction and support provided by the website. User will comment about the website, based on the comment system will rate the website. The system takes opinion of various users, based on the opinion; system will decide whether the website is genuine or not. The system uses opinion mining methodology in order to achieve desired functionality.','false');

insert into Project values(75,'Sentiment Analysis for Product Rating','2015-01-02','Completed','Here we propose an advanced Sentiment Analysis for Product Rating system that detects hidden sentiments in comments and rates the product accordingly. The system uses sentiment analysis methodology in order to achieve desired functionality. This project is an E-Commerce web application where the registered user will view the product and product features and will comment about the product. System will analyze the comments of various users and will rank product. We use a database of sentiment based keywords along with positivity or negativity weight in database and then based on these sentiment keywords mined in user comment is ranked. Comment will be analyzed by comparing the comment with the keywords stored in database. The System takes comments of various users, based on the comment, system will specify whether the product is good, bad, or worst.','true');

insert into Project values(76,'Opinion Mining For Automated Restaurant Reviews Rating','2014-12-09','Completed','Here we propose an advanced Restaurant Review system that detects hidden sentiments in feedback of the customer and rates the restaurant accordingly. The system uses opinion mining methodology in order to achieve desired functionality. Opinion Mining for Restaurant Reviews is a web application which gives review of the feedback that is posted. The System takes feedback of various users, based on the opinion, system will specify whether the posted restaurant is good, bad, or worst. We use a database of sentiment based keywords along with positivity or negativity weight in database and then based on these sentiment keywords mined in user feedback is ranked.','true');

insert into Project values(77,'Monitoring Suspicious Discussions On Online Forums Using Data Mining','2015-08-08','Ongoing','People now-a-days are very fond of using internet as a discussion medium. As internet technology had been increasing more and more, this technology led to many legal and illegal activities. It is found that much first-hand news has been discussed in Internet forums well before they are reported in traditional mass media. This communication channel provides an effective channel for illegal activities such as dissemination of copyrighted movies, threatening messages and online gambling etc. The law enforcement agencies are looking for solutions to monitor these discussion forums for possible criminal activities and download suspected postings as evidence for investigation. We propose a system which will tackle this problem effectively. In this project we had used a data mining algorithm to detect criminal activities and illegal postings.','false');

insert into Project values(78,'Opinion Mining For Comment Sentiment Analysis','2015-07-07','Completed','Here we propose an advanced Comment Sentiment Analysis system that detects hidden sentiments in comments and rates the post accordingly. The system uses opinion mining methodology in order to achieve desired functionality. Opinion Mining for Comment Sentiment Analysis is a web application which gives review of the topic that is posted by the user. The System takes comments of various users, based on the opinion, system will specify whether the posted topic is good, bad, or worst. We use a database of sentiment based keywords along with positivity or negativity weight in database and then based on these sentiment keywords mined in user comment is ranked. Once the user logins to the system, user can view his own status as well as he can view the topics posted by the admin. When the user clicks on a particular topic user can give his own comment about the topic. System will use database and will match the comment with the keywords in database and will rank the topic. User can edit his own profile and can change his profile picture. The role of the admin is to add post and adds keywords in database.','true');

insert into Project values(79,'Biomedical Data Mining For Web Page Relevance Checking','2016-02-28','Ongoing','Web mining and data mining go hand in hand when creating web mining systems.Websites created in various platforms have different data structures and are difficult to read for a single algorithm. Since it is not feasible to build a different algorithm to suit various web technology we need to use efficient web mining algorithms to mine this huge amount of web data. Web pages are made up of HTML (Hyper text markup language) In various arrangements and have images, videos etc intermixed on a single web page. So we here propose to use smartly designed web mining algorithms to mine textual information on web pages and detect their relevancy to biomedical sector. In this way we may judge web pages and check their relevancy to the biomedical field. This system proves useful in many biomedical sectors and even search engines to classify web pages into the biomedical structure. Their relevancy to the field help classify and sort them appropriately for the sector.','false');

insert into Project values(80,'Web Mining For Suspicious Keyword Prominence','2014-11-11','Completed','This project consolidates the best researched mechanisms from the semantic web and synaptic web at low entropy in order to build structural engineering of Semantic-Synaptic web mining. Our proposed project aims at web mining for finding out density of selected keywords in order to check its keyword prominence on those web pages. This is an important factor in various fields in order to check the prominence of specific keywords and flag websites having over prominence of those keywords. For example this can also be used to detect websites inspiring terrorism. The system can be used to check prominence of a particular keyword commonly used in terrorist convincing strategies on various websites. So this system can be used to point out websites having more prominence of such keywords','true');





