# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import se1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatid', models.IntegerField(primary_key=True, serialize=False)),
                ('usn', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('chatcontent', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('projid', models.IntegerField(primary_key=True)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('domid', models.IntegerField(primary_key=True, serialize=False)),
                ('domainname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilesUpload',
            fields=[
                ('fileid', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=se1.models.content_file_name)),
                ('projid', models.IntegerField()),
            ],
            options={
                'db_table': 'filesupload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profcontact',
            fields=[
                ('profid', models.IntegerField()),
                ('phno', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profcontact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profemail',
            fields=[
                ('profid', models.IntegerField(primary_key=True)),
                ('email', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profemail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profidea',
            fields=[
                ('idea', models.TextField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('newprojid', models.IntegerField(primary_key=True, serialize=False)),
                ('profid', models.IntegerField()),
            ],
            options={
                'db_table': 'profidea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profinfo',
            fields=[
                ('profid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('passwd', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'projdom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('dateofreg', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('complete', models.NullBooleanField()),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.IntegerField()),
                ('fpath', models.TextField(blank=True, null=True)),
                ('adate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projprof',
            fields=[
                ('projid', models.IntegerField(primary_key=True)),
                ('profid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'projprof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projprofcom',
            fields=[
                ('comment', models.TextField(blank=True, null=True)),
                ('projid', models.IntegerField()),
                ('profid', models.IntegerField()),
                ('commentid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'projprofcom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studcontact',
            fields=[
                ('phno', models.IntegerField(primary_key=True, serialize=False)),
                ('usn', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'studcontact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studemail',
            fields=[
                ('usn', models.CharField(max_length=10)),
                ('email', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'studemail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('passwd', models.TextField(blank=True, null=True)),
                ('sem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studentinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studprojgrade',
            fields=[
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('usn', models.CharField(max_length=10)),
                ('projid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'studprojgrade',
                'managed': False,
            },
        ),
    ]
